### ISSUE TITLE
End-user instructions?

### ISSUE THREAD

**Issue by dandv** [merceyz/typescript-to-proptypes#19]
How should this package be used?

Is this library equivalent to @gcanti's [prop-types-ts](https://github.com/gcanti/prop-types-ts) or [babel-plugin-typescript-to-proptypes](https://github.com/milesj/babel-plugin-typescript-to-proptypes) from @milesj?

**Comment by NMinhNguyen** [comment]
@dandv if you're currently in a rush to use this, I'd say take a look at how it's being used in https://github.com/mui-org/material-ui/ for the time being.

**Comment by merceyz** [comment]
This project was mostly made to get rid of the PropTypes from the TypeScript demos of Material-UI (https://github.com/mui-org/material-ui/pull/16521).

> How should this package be used?

I haven't really documented the project but there are tests that showcase how to use it [1]. You can also look at how it's setup in Material-UI to handle their needs [2][3]

1. https://github.com/merceyz/typescript-to-proptypes/blob/66f228715a14dd5883d7c06a2b19e6439938973f/test/index.test.ts
2. https://github.com/mui-org/material-ui/blob/2231349c302a089cc556614ff562b02a729b1e77/docs/scripts/formattedTSDemos.js
3. https://github.com/mui-org/material-ui/blob/2231349c302a089cc556614ff562b02a729b1e77/scripts/generateProptypes.ts

> Is this library equivalent to gcanti's prop-types-ts or babel-plugin-typescript-to-proptypes from milesj?

No, `prop-types-ts` requires you to write special syntax to get both types and PropTypes while `babel-plugin-typescript-to-proptypes` can only get info from the current file. This project uses the TypeScript compiler API to get all the information it needs from your entire project and builds up the PropTypes from it.

**Comment by aschmoe** [comment]
For anyone coming upon this PR / comment later, here is an example usage:

https://gist.github.com/aschmoe/81e51ca4406a2ffef0019f7260d6d14b

working as of:`"typescript-to-proptypes": "^2.2.1"` (though definitely struggles with complicated type definitions, unsurprisingly)
