### ISSUE TITLE
Add to existing .tsx file

### ISSUE THREAD

**Issue by clintandrewhall** [merceyz/typescript-to-proptypes#24]
I've been poking around in the source, and I don't see any means of not completely transpiling code to JS.  What I'd _like_ to do is add these prop types to a `tsx` file.

I can continue to poke around, but I wanted to raise the question in case it had a quick answer.  Great tool, hoping to use it more!

**Comment by merceyz** [comment]
> I can continue to poke around, but I wanted to raise the question in case it had a quick answer

I'm afraid poking around the source would have been faster, sorry about that

> I've been poking around in the source, and I don't see any means of not completely transpiling code to JS. What I'd like to do is add these prop types to a tsx file.

After you use the parser to get the AST you can point the injector at any valid source code, you just need to provide it with the babel plugins required to understand it.
https://github.com/merceyz/typescript-to-proptypes/blob/d02a08a7f4c7a25e08c786fa8b625d838613c8b5/src/injector.ts#L45-L48
https://github.com/merceyz/typescript-to-proptypes/blob/d02a08a7f4c7a25e08c786fa8b625d838613c8b5/src/injector.ts#L75
