### ISSUE TITLE
typescript as peer dependency?

### ISSUE THREAD

**Issue by benmvp** [merceyz/typescript-to-proptypes#28]
Have you considered making `typescript` a peer dependency instead of main dependency?

The reason I ask is because type-only imports/export that was introduced in [TS@3.8](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export). And since this package is explicitly using [`typescript@3.5.2`](https://github.com/merceyz/typescript-to-proptypes/blob/93fb992ee85787d3049eef9577faf68b18545760/package.json#L56), it was unable to retrieve type information for the majority of my React components. Let's just say it took a looooong time to figure that out. 😅 

I was going to figure put a PR that upgraded to the latest version of `typescript`, but then wondered why not make `typescript` a peer dep so it'll just use the version in the host app? Thoughts?

Thanks so much for this package! It's saved me from having to duplicate TS types & `PropTypes` 🎉

**Comment by merceyz** [comment]
The issue is that the TypeScript API i'm using isn't stable and it can change at any time, which would be even worse to debug so I locked it to a working version. If you want to make a PR that updates the version to one that still works / alter it to work I'd happily accept it :+1:

**Comment by benmvp** [comment]
Awesome! I'll give that a shot and see how it turns out.

And yeah that totally makes sense about the TS API. Didn't think about that...

**Comment by benmvp** [comment]
Done! #29
