### ISSUE TITLE
instanceOf(Element) doesn't work in iframe

### ISSUE THREAD

**Issue by oliviertassinari** [merceyz/typescript-to-proptypes#3]
@merceyz I have noticed a warning with this demo https://material-ui.com/components/drawers/#responsive-drawer which lead my track down to:

https://github.com/merceyz/typescript-to-proptypes/blob/adfcca429fca9b1734e361547d19fb9a79a335be/src/parser.ts#L355-L358

`instanceOf(Element)` doesn't work with different documents, e.g. iframe: https://github.com/facebook/prop-types/issues/240#issuecomment-524997768.

We were able to work around the problem in the Popper component with: https://github.com/mui-org/material-ui/blob/c1c66903b8cc3941d0e110f13f49122effdc0e47/packages/material-ui/src/Popper/Popper.js#L238. 

Any idea on how we could best solve this problem?

**Comment by FezVrasta** [comment]
This is how we address the iframe problem in Popper 2 if it can be useful to you.

https://github.com/popperjs/popper-core/blob/master/src/dom-utils/instanceOf.js

**Comment by merceyz** [comment]
@oliviertassinari Thanks for the report, seems the only way to handle this is using a custom validator. I'll look into solving this when I have some more time.

**Comment by oliviertassinari** [comment]
@merceyz Thanks, I suspect that a generic and loose validator could be a great tradeoff. It's what the Portal component used to have.
A more comprehensive solution might depends on #1.
