### ISSUE TITLE
need support for optional prop types

### ISSUE THREAD

**Issue by naveen-bharathi** [merceyz/typescript-to-proptypes#32]
currently, all the fields specified in a type are considered as required and 'isRequired' is added to each proptype generated, even though the field is optional.

## Current Behaviour
The following type
```typescript
type Props = {
  alignBottom?: boolean
  alignCenter: boolean
  alignTop: boolean
}
```
is generated as
```javascript
{
  alignBottom: PropTypes.bool.isRequired,
  alignCenter: PropTypes.bool.isRequired,
  alignTop: PropTypes.bool.isRequired,
}
```

## Expected Behaviour
The following type
```typescript
type Props = {
  alignBottom?: boolean
  alignCenter: boolean
  alignTop: boolean
}
```
should be generated as
```javascript
{
  alignBottom: PropTypes.bool,
  alignCenter: PropTypes.bool.isRequired,
  alignTop: PropTypes.bool.isRequired,
}
```

**Comment by merceyz** [comment]
It already supports optional types, ref the fixture here https://github.com/merceyz/typescript-to-proptypes/blob/c53bfa8f5f90da13e3fc39ccd44dacee73c492e3/test/boolean-values/optional. I'm guessing you haven't enabled strict mode so typescript doesn't actually detect undefined

**Comment by naveen-bharathi** [comment]
@merceyz In strict mode, it works perfect. You can now close this issue.
